name: Python app
on:
push:
branches: [ "main" ]
pull_request:
branches: [ "main" ]
workflow_dispatch:
jobs:
build:
runs-on: ubuntu-latest
strategy:
fail-fast: false
matrix:
python-version: ["3.10"]
steps:
- name: Checkout step to clone repo
uses: actions/checkout@v3
- name: Set up Python ${{ matrix.python-version }}
uses: actions/setup-python@v3
with:
python-version: ${{ matrix.python-version }}
- name: Install dependencies
run: |
pip install -r bikeshare_project/requirements/test_requirements.txt
- name: Train pipeline
run: |
python bikeshare_project/bikeshare_model/train_pipeline.py
- name: Test with pytest
run: |
pytest
- name: Format code with Black
run: |
black bikeshare_project/bikeshare_model/*.py
- name: Lint with pylint
run: |
pylint --disable=R,C
bikeshare_project/bikeshare_model/{pipeline,train_pipeline,predict}.py
